C---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through deConz.

# | Button   | Action              |
# | -------- | ------------------- |
# | Power    | Toggle the light    |
# | Dim-Up   | Increase brightness |
# | Dim-Down | Decrease brightness |
# | Right    | Change color        |
# | Left     | Change saturation   |

blueprint:
  #source_url: https://github.com/niro1987/homeassistant-config/blob/master/blueprints/automation/niro1987/zha_ikea_tradfri_5button_remote_color.yaml
  source_url: https://github.com/vdGeld/homeassistant-config/edit/master/blueprints/automation/niro1987/deConz_ikea_tradfri_5button_remote_color.yaml

  name: deConz - IKEA TRADFRI - 5 Button Remote - Color Lights

  description: >-
    This automation simulates the use of the IKEA TRADFRI remote control
    connected through deConz.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: deconz
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

variables:
  var_light: !input light

trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input remote

action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      # Short-Press on the power button.
      - conditions:
          - "{{ event == 1002 }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light

      # Long-Press on the power button.
      - conditions:
          - "{{ event == 1001 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness: 254
              hs_color:
                - 38.222
                - 52.941

      # Short-Press on the dim-up button.
      - conditions:
          - "{{ event == 2002 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: 20
              transition: 0.5

      # Long-Press on the dim-up button.
      - conditions:
          - "{{ event == 2001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # Short-Press on the dim-down button.
      - conditions:
          - "{{ event == 3002 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: -20
              transition: 0.5

      # Long-Press on the dim-down button.
      - conditions:
          - "{{ event == 3001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # Short-Press on the color-up button.
      - conditions:
          - "{{ event == 5002 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              hs_color:
                - >-
                  {% if state_attr(var_light, "hs_color")[0] + 18 > 360 %}
                    {{ state_attr(var_light, "hs_color")[0] + 18 - 360 }}
                  {% else %}
                    {{ state_attr(var_light, "hs_color")[0] + 18 }}
                  {% endif %}
                - '{{ state_attr(var_light, "hs_color")[1] }}'
              transition: 0.5

      # Long-Press on the color-up button.
      - conditions:
          - "{{ event == 5001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    hs_color:
                      - >-
                        {% if state_attr(var_light, "hs_color")[0] + 18 > 360 %}
                          {{ state_attr(var_light, "hs_color")[0] + 18 - 360 }}
                        {% else %}
                          {{ state_attr(var_light, "hs_color")[0] + 18 }}
                        {% endif %}
                      - '{{ state_attr(var_light, "hs_color")[1] }}'
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # Short-Press on the color-down button.
      - conditions:
          - "{{ event == 4002 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              hs_color:
                - '{{ state_attr(var_light, "hs_color")[0] }}'
                - >-
                  {% if state_attr(var_light, "hs_color")[1] - 20 < 0 %}
                    {{ state_attr(var_light, "hs_color")[1] - 20 + 100 }}
                  {% else %}
                    {{ state_attr(var_light, "hs_color")[1] - 20 }}
                  {% endif %}
              transition: 0.5

      # Long-Press on the color-down button.
      - conditions:
          - "{{ event == 4001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    hs_color:
                      - '{{ state_attr(var_light, "hs_color")[0] }}'
                      - >-
                        {% if state_attr(var_light, "hs_color")[1] - 10 < 0 %}
                          {{ state_attr(var_light, "hs_color")[1] - 10 + 100 }}
                        {% else %}
                          {{ state_attr(var_light, "hs_color")[1] - 10 }}
                        {% endif %}
                    transition: 0.5
                - delay:
                    milliseconds: 500

    # Any other event will cancel the repeat loops.
    default: []
